Docs: Diagram Storage
erpya/adempiere-ui-gateway pull request #81
Opened 2024-04-08 20:10 UTC by Ricargame

![image](https://github.com/adempiere/adempiere-ui-gateway/assets/78000356/c005eccd-d004-4099-a978-5f8af10b4462)

2024-04-09 03:37 UTC, marcalwestf commented
@Ricargame : the image  looks god.
I would suggest that you insert it in the README.md file, so it can be seen by everybody.
Thanks!!!

2024-04-09 18:53 UTC, EdwinBetanc0urt requested changes
@Ricargame  please remove kafka and zookeper from the diagram services, they are not part of that stack.

2024-04-09 20:32 UTC, Ricargame commented
hi @marcalwestf  This is a chapter of how the diagram turned out.

![image](https://github.com/adempiere/adempiere-ui-gateway/assets/78000356/56472fa2-d338-41fa-80b7-31a3c9e3448f)

2024-04-09 20:37 UTC, EdwinBetanc0urt approved these changes

2024-04-10 14:10 UTC, marcalwestf approved these changes

2024-04-10 14:11 UTC, merged